# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Images
    jobs:
      - job: BuildAndPushDockerImages
        displayName: Build and Push Docker Images to Docker Hub
        steps:
          - checkout: self

          - script: |
              sudo -y docker login -u bhandarenakul -p $(DOCKER_PASSWORD)
            displayName: "Build & Push Docker Images"

  - stage: Deploy
    displayName: Deploy to Azure VM
    dependsOn: BuildAndPush
    jobs:
      - deployment: DeployToVM
        displayName: Deploy to Azure Virtual Machine
        environment:
         name: testing
         resourceName: sproutly
         resourceType: virtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - script: |
                    sudo -y docker login -u bhandarenakul -p $(DOCKER_PASSWORD)

                    # Run Docker Compose
                    sudo docker-compose -f docker-compose.yml up -d
                  displayName: "Deploy Application"
