name: Create Weekly Issues

on:
  schedule:
    - cron: "0 12 * * 5" # Runs every Friday at 12:00 UTC

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the latest issue number
        id: get-issue-number
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues?state=all)
          echo "$response" | jq -r 'map(select(.title | startswith("[User Story] - Sprint Demo #")) | .title | capture("#(?<num>[0-9]+)").num | tonumber) | max' || echo "0"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create weekly issue
        uses: actions/github-script@v6
        with:
          script: |
            // Parse the last issue number and increment
            const lastIssueNumber = parseInt("${{ steps.get-issue-number.outputs.stdout }}", 10) || 0;
            const newIssueNumber = lastIssueNumber + 1;

            // Create the issue
            const { data: issue } = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[User Story] - Sprint Demo #${newIssueNumber}`,
              body: `
### Epic Link:

#17

### User Story

As a Client, I want to see the weekly progress, so that I can give fast feedback.

### Task Links:
              `.trim(),
            });

            core.info(`Created issue #${issue.number}`);
