name: Create Weekly Issues

on:
  schedule:
    - cron: "0 12 * * 5" # Runs every Friday at 12:00 UTC

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create weekly issue
        uses: actions/github-script@v6
        with:
          script: |
            const existingIssues = await github.paginate(github.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "all"
            });

            // Find the latest issue number from the title
            const lastIssue = existingIssues
              .map(issue => issue.title.match(/\[User Story\] - Sprint Demo #(\d+)/))
              .filter(match => match)
              .map(match => parseInt(match[1], 10))
              .reduce((max, num) => Math.max(max, num), 0);

            const newIssueNumber = lastIssue + 1;

            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[User Story] - Sprint Demo #${newIssueNumber}`,
              body: `
### Epic Link:

#17

### User Story

As a Client, I want to see the weekly progress, so that I can give fast feedback.

### Task Links:
              `.trim(),
            });

            core.info(`Created issue [User Story] - Sprint Demo #${newIssueNumber}`);
