name: Create Weekly Issues

on:
  schedule:
    - cron: "0 12 * * 5" # Runs every Friday at 12:00 UTC

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create weekly issue
        uses: actions/github-script@v6
        with:
          script: |
            const lastIssueNumber = 1; // Adjust this number manually if needed
            const newIssueNumber = lastIssueNumber + 1;

            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[User Story] - Sprint Demo #${newIssueNumber}`,
              body: `
### Epic Link:

#17

### User Story

As a Client, I want to see the weekly progress, so that I can give fast feedback.

### Task Links:
              `.trim(),
            });
